 -
  title: "About"
  link: "/about"
  items:
   -
    title: "About the ODI"
    link: "/about-us"
   -
    title: "Team"
    link: "/team"
   -
    title: "Jobs"
    link: "/jobs"
   -
    title: "Annual Report"
    link: "/odis-first-year-annual-report"
   -
     title: "Procurement"
     link: "/procurement"
   -
     title: "Data as culture"
     link: "/culture"
   -
     title: "Space"
     link: "/space"
   -
     title: "FAQ"
     link: "/faq"
   -
     title: "Dashboards"
     link: "http://dashboards.theodi.org/"
 - 
   title: "Get involved"
   link: "/get-involved"
   items:
    -
     title: "Membership"
     link: "/join-us"
    -
     title: "Our members"
     link: "http://directory.theodi.org/members"
    -
     title: "Startups"
     link: "/start-ups"
    -
     title: "Research"
     link: "/research"
    -
     title: "Open Data Certificates"
     link: "https://certificates.theodi.org/"
    -
     title: "Nodes"
     link: "/nodes"
    -
     title: "Challenge series"
     link: "/opendatachallengeseries"
    -
     title: "Public consultations"
     link: "/public-consultations"
    -
     title: "Consultation responses"
     link: "/consultation-responses"
    -
     title: "Partnership for Open Data"
     link: "http://theodi.org/odp4d"
 - 
  title: "Learning & courses"
  link: "/courses"
  items:
   -
    title: "Courses"
    link: "/courses"
   -
    title: "International courses"
    link: "/international-courses"
   -
    title: "In-house training"
    link: "/in-house-training"
   -
    title: "Friday lunchtime lectures"
    link: "/lunchtime-lectures"
   - 
    title: "Guides"
    link: "/guides"
   - 
    title: "Training FAQs"
    link: "/training-faqs"
   - 
    title: "ODI registered trainers"
    link: "/what-is-an-odi-registered-trainer"
 - 
  title: "What's happening"
  link: "/events"
  items:
   -
    title: "Previous events"
    link: "/events/previous"
 - 
  title: "News & blog"
  link: "/news"
  items:
   -
    title: "International node news"
    link: "/nodes/news"
   -
    title: "Open data stories"
    link: "/stories"
   - 
    title: "Case studies"
    link: "/case-studies"
   -
    title: "Media assets"
    link: "/newsroom"
