 -
  title: "About"
  link: "/about"
  items:
   -
    title: "About the ODI"
    link: "/about-us"
   -
    title: "Team"
    link: "/team"
   -
    title: "Jobs"
    link: "/jobs"
   -
     title: "Procurement"
     link: "/procurement"
   -
     title: "Data as culture"
     link: "/culture"
   -
     title: "Space"
     link: "/space"
   -
     title: "FAQ"
     link: "/faq"
   -
     title: "Dashboards"
     link: "http://dashboards.theodi.org/"
 - 
   title: "Get involved"
   link: "/get-involved"
   items:
    -
     title: "Membership"
     link: "/join-us"
    -
     title: "Our members"
     link: "http://directory.theodi.org/members"
    -
     title: "Startups"
     link: "/start-ups"
    -
     title: "Research"
     link: "/research"
    -
     title: "Open Data Certificates"
     link: "https://certificates.theodi.org/"
    -
     title: "Nodes"
     link: "/nodes"
    -
     title: "Challenge series"
     link: "/opendatachallengeseries"
    -
     title: "Public consultations"
     link: "/public-consultations"
    -
     title: "Consultation responses"
     link: "/consultation-responses"
    -
     title: "Partnership for Open Data"
     link: "http://theodi.org/odp4d"
 - 
  title: "What we offer"
  link: "/courses"
  items:
   -
    title: "Courses"
    link: "/courses"
   -
    title: "In-house training"
    link: "/in-house-training"
   - 
    title: "Meet the trainers"
    link: "/training_team"
   - 
    title: "Training FAQs"
    link: "/training-faqs"
   - 
    title: "Services"
    link: "/services"
 - 
  title: "Publications"
  link: "/publications"
  items:
   -
    title: "Guides"
    link: "/guides"
   -
    title: "Case Studies"
    link: "/case-studies"
   - 
    title: "Open Data Stories"
    link: "/stories"
   -
    title: "Open Data Roadmap 2015"
    link: "/roadmap-uk-2015"
   -
    title: "Annual Report 2014"
    link: "/odis-second-year-annual-report"
   -
    title: "Annual Report 2012-13"
    link: "/odis-first-year-annual-report"
 - 
  title: "What's happening"
  link: "/events"
  items:
   -
    title: "Friday lunchtime lectures"
    link: "/lunchtime-lectures"
   -
    title: "Previous events"
    link: "/events/previous"
 - 
  title: "News & blog"
  link: "/news"
  items:
   -
    title: "International node news"
    link: "/nodes/news"
   -
    title: "Media assets"
    link: "/newsroom"
