 -
  title: "About"
  link: "/about"
  items:
   -
    title: "About the ODI"
    link: "/about-us"
   -
    title: "Team"
    link: "/team"
   -
    title: "Jobs"
    link: "/jobs"
   -
    title: "Annual Report"
    link: "/odis-first-year-annual-report"
   -
     title: "Procurement"
     link: "/procurement"
   -
     title: "Data as culture"
     link: "/culture"
   -
     title: "Space"
     link: "/space"
   -
     title: "FAQ"
     link: "/faq"
   -
     title: "Dashboards"
     link: "http://dashboards.theodi.org/"
 - 
   title: "Get involved"
   link: "/get-involved"
   items:
    -
     title: "Membership"
     link: "/join-us"
    -
     title: "Our members"
     link: "http://directory.theodi.org/members"
    -
     title: "Startups"
     link: "/start-ups"
    -
     title: "Research"
     link: "/research"
    -
     title: "Open Data Certificates"
     link: "https://certificates.theodi.org/"
    -
     title: "Nodes"
     link: "/nodes"
    -
     title: "Challenge series"
     link: "/challenge-series"
    -
     title: "Consultation responses"
     link: "/consultation-responses"
    -
     title: "Partnership for Open Data"
     link: "http://theodi.org/blog/partnership-for-open-data-impact-stories-competition"
 - 
  title: "Learning & courses"
  link: "/learning"
  items:
   -
    title: "Courses"
    link: "/courses"
   -
    title: "Friday lunchtime lectures"
    link: "/lunchtime-lectures"
   - 
    title: "Guides"
    link: "/guides"
   - 
    title: "Case studies"
    link: "/case-studies"
   - 
    title: "Training FAQs"
    link: "/training-faqs"
 - 
  title: "What's happening"
  link: "/events"
  items:
   -
    title: "Previous events"
    link: "/events/previous"
 - 
  title: "News & blog"
  link: "/news"
  items:
    -
      title: "Media assets"
      link: "/newsroom"
